language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py27
install:
  - pip install pip setuptools wheel -U
  - pip install tox
script:
  - tox
